extends Node

enum STARTUP_MODE { MAP_EDITOR, GAME, DEVELOPMENT }
enum PARTY_STATE { IDLE, MOVED }
enum CLASSES { NONE, WARRIOR, KNIGHT, WIZARD, HUNTER, THIEF, CLERIC }
enum CLASSES_ATTRIBUTE_GROWTH { NONE, FLAT, NORMAL, SHARP }
enum SYSTEM_SKILL_CHECK_RESULT { FAIL, SUCCESS, CRITICAL }
enum AGES { YOUNG, ADULT, OLD }
enum SAVE_SLOTS { SLOT1, SLOT2, SLOT3 }
enum MAPS { NONE, DEV_MAP }
enum ENTER_FROM { START_SCREEN }
enum SCENE_TYPE {
	PARTY,
	PLAYER_SPRITE
}
