extends Node

var SYSTEM_NEW_GAME:String = "New game"
var SCENE_WORLDS_PATH:String = "res://scenes/worlds/"
var SCENE_DEV_WORLD:String = "devWorld.tscn"


var CHARACTER_AGE_YOUNG:String = "Young"
var CHARACTER_AGE_ADULT:String = "Adult"
var CHARACTER_AGE_OLD:String = "Old"

var CLASS_WARRIOR_NAME_1:String = "Goor"
var CLASS_WARRIOR_NAME_2:String = "Friez"
var CLASS_WARRIOR_NAME_3:String = "Pronc"
var CLASS_WARRIOR_NAME_4:String = "Klug"

var CLASS_KNIGHT_NAME_1:String = "Rhono"
var CLASS_KNIGHT_NAME_2:String = "Tulio"
var CLASS_KNIGHT_NAME_3:String = "Wrex"
var CLASS_KNIGHT_NAME_4:String = "Plias"

var CLASS_HUNTER_NAME_1:String = "Rux"
var CLASS_HUNTER_NAME_2:String = "Onni"
var CLASS_HUNTER_NAME_3:String = "Mida"
var CLASS_HUNTER_NAME_4:String = "Ainro"

var CLASS_WIZARD_NAME_1:String = "Xro"
var CLASS_WIZARD_NAME_2:String = "Rux"
var CLASS_WIZARD_NAME_3:String = "Dilio"
var CLASS_WIZARD_NAME_4:String = "Qaz"

var CLASS_THIEF_NAME_1:String = "Pik"
var CLASS_THIEF_NAME_2:String = "Tyr"
var CLASS_THIEF_NAME_3:String = "Elis"
var CLASS_THIEF_NAME_4:String = "Lios"

var CLASS_CLERIC_NAME_1:String = "Rhina"
var CLASS_CLERIC_NAME_2:String = "Olona"
var CLASS_CLERIC_NAME_3:String = "Hemic"
var CLASS_CLERIC_NAME_4:String = "Plax"

var MAP_TRAVEL_EAST:String = "Traveling east."
var MAP_TRAVEL_NORTH:String = "Traveling north."
var MAP_TRAVEL_WEST:String = "Traveling west."
var MAP_TRAVEL_SOUTH:String = "Traveling south."

var ALWAYS = "Any"
var NEVER = "Never"
var SELF_HP_GT_50 = "Self:HP > 50%"
var SELF_HP_GT_20 = "Self:HP > 20%"
var SELF_HP_LT_80 = "Self:HP < 80%"
var SELF_HP_LT_50 = "Self:HP < 50%"
var SELF_HP_LT_20 = "Self:HP < 20%"
var SELF_HP_LT_10 = "Self:HP < 10%"
var SELF_MP_GT_50 = "Self:MP > 50%"
var SELF_MP_GT_20 = "Self:MP > 20%"
var SELF_MP_LT_80 = "Self:MP < 80%"
var SELF_MP_LT_50 = "Self:MP < 50%"
var SELF_MP_LT_20 = "Self:MP < 20%"
var SELF_MP_LT_10 = "Self:MP < 10%"
var ALLY_HP_GT_50 = "Ally:HP > 50%"
var ALLY_HP_GT_20 = "Ally:HP > 20%"
var ALLY_HP_LT_80 = "Ally:HP < 80%"
var ALLY_HP_LT_50 = "Ally:HP < 50%"
var ALLY_HP_LT_20 = "Ally:HP < 20%"
var ALLY_HP_LT_10 = "Ally:HP < 10%"
var ALLY_MP_GT_50 = "Ally:MP > 50%"
var ALLY_MP_GT_20 = "Ally:MP > 20%"
var ALLY_MP_LT_80 = "Ally:MP < 80%"
var ALLY_MP_LT_50 = "Ally:MP < 50%"
var ALLY_MP_LT_20 = "Ally:MP < 20%"
var ALLY_MP_LT_10 = "Ally:MP < 10%"
var ALLY_DEAD = "Ally:Dead"

var NONE = ""
var ATTACK = "Attack"
var USE_POTION_SELF = "Use potion self"
var USE_POTION_ALLY = "Use potion ally"
var USE_HERB_SELF = "Use herb self"
var USE_HERB_ALLY = "Use herb ally"
var USE_ELEXIR_ALLY = "Use elexir"
var CAST_FIREBALL = "case fireball"
var PROTECT = "protect"
var DEFEND = "defend"

